---
title: "PS270 Final Project"
author: "Lalitha Viswanathan"
description: "My final project"
output:    
  distill::distill_article: 
    self_contained: false
---



## Project thoughts
 
I am interested in exploring data related to Super Bowl ads, 2015 Women's World Cup predictions, and regional studies of the US. I was looking through the different types of data available on FiveThirtyEight, and they had really interesting data sets available. I would love to follow the one about women's soccer as a former soccer player, but also regional studies. There was one that caught my eye about regional differences around the U.S. for Thanksgiving, and that sounded really cool. I'm from New Jersey, and I love getting to talk to people from around the country about the differences between things that we each find normal

```{r}
library(tidyverse)
judicial_data <- read_csv("data/data.csv")

head(judicial_data)

```

## Proposal

This research is from the Tuck School at Dartmouth, a paper entitled, "Judicial Checks and Balances," published in 2004. 

Research question I would want to know: Are countries with high ethnolinguistic fractionalization (diversity) more likely to have low human rights indexes?
Hypothesis: I hypothesize that countries with very low ethnolinguistic fractionalization are more likely to have higher human rights indexes, and that countries with medium and high ethnolinguistic fractionalization would have low human rights indexes. For societies with low diversity, I think there would be less human rights abuses because the society is homogeneous. On the alternative, I think that heterogeneous countries, having two or more ethnolinguistic groups, would be more likely to have more human rights abuses because groups could be turned against each other, and in some countries, the majority group would inflict pain or abuses on the minority groups that do not have much power. 

The explanatory variable is the ethnolinguistic fractionalization. This is the method the researchers used to track it: "Average value of five different indices of ethnolinguistic fractionalization. Its value ranges from 0 to 1. The five component indices are: (1) index of ethnolinguistic fractionalization in 1960, which measures the probability that two randomly selected people from a given country will not belong to the same ethnolinguistic group (the index is based on the number and size of population groups as distinguished by their ethnic and linguistic status); (2) and (3) probability of two randomly selected individuals speaking different languages; (4) percent of the population not speaking the official language; and (5) percent of the population not speaking the most widely used language. Sources: Easterly and Levine (1997)."
The outcome variable of interest is the Human Rights Index and this is how it was measured: "A measure of 37 criteria based on the rights enumerated in the three major UN treaties: 1948 Universal Declaration of Human Rights, 1996 International Covenant on Civil and Political Rights, International Covenant on Economics, Social, and Cultural Rights. Ranges from 17 to 99 in the sample, with higher scores indicating better human rights. Source: Humana (1992)." 

Each of the descriptions of the methodology that the researchers used are taken from this website: https://faculty.tuck.dartmouth.edu/images/uploads/faculty/rafael-laporta/jcb_variable_description.pdf

The observed pattern in the data that would provide support for my hypothesis would be that when the ethnolinguistic diversity goes up, the Human Rights Index goes down, meaning that when there's more diversity, there are more human rights abuses. One observed pattern that would disprove my hypothesis would be countries being extremely homogeneous, meaning they have a low ethnolinguistic fractionalization score, and also having a low human rights index score.

